services:

  samba:
    image: dperson/samba
    restart: always
    command:
      - -u
      - 'darkvice;${SAMBA_PASS}'
      - -s
      - media;/media;yes;no;no;darkvice;none
      - -s
      - downloads;/downloads;yes;no;no;darkvice;none
      - -s
      - datos;/mnt;yes;no;no;darkvice;none
      - -g
      - 'workgroup = WORKGROUP'   # reemplaza WORKGROUP si tu Windows usa otro
      - -g
      - map to guest = Bad User
      - -g
      - create mask = 0664
      - -g
      - directory mask = 0775
      - -g
      - vfs objects = acl_xattr
      - -g
      - store dos attributes = yes
      - -g
      - map acl inherit = yes
      - -g
      - 'force user = darkvice'
      - -g
      - 'force group = darkvice'
      - -g
      - 'hosts allow = 192.168.1.0/24 127.0.0.1'
      - -g
      - 'client min protocol = SMB2_10'
      - -g
      - 'server min protocol = SMB2_10'
      - -r
    environment:
      - TZ=America/Lima
      - PUID=1000
      - PGID=1000
    ports:
      - 192.168.1.10:137:137/udp
      - 192.168.1.10:138:138/udp
      - 192.168.1.10:139:139
      - 192.168.1.10:445:445
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads
      - /DATA_NAS/datos:/mnt
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  plex:
    image: jaymoulin/plex:1.30.1.6562
    expose:
      - 32400
      - 33400
    # Descomentar si NO usas network_mode: "host"
    # ports:
    #  - 32400:32400
    #  - 33400:33400
    hostname: plex
    environment:
      - TZ=America/Lima
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host" # Solo funciona en Linux

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ${STORAGE}/transmission_config:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 192.168.1.10:9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.5
    volumes:
      - ${STORAGE}/flexget_config:/config
      - ${STORAGE}/flexget_config/config-trakt.yml:/config/config-trakt.yml # <--- ¡CORREGIDO para ir al ZFS!
      - /opt/lsio-flexget-init/mediainfo.sh:/custom-cont-init.d/mediainfo.sh:ro # <--- Esta se mantiene desde el repositorio
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 192.168.1.10:5050:5050
    environment:
      - TZ=America/Lima
      - PUID=1000
      - PGID=1000
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=${FLEXGET_WEBUI_PASS} # la puedes cambiar por la que quieras
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
